import type { Report } from "@/types/report";

export const seededReports: Report[] = [
  {
    id: "seed-1",
    userId: "matan",
    userEmail: "matan@example.com",
    reporterName: "מתן",
    role: "מתעד שטח",
    facility: "organized-toilet",
    sittingTime: "up-to-5",
    peeTiming: "during",
    entertainment: "phone",
    color: "dark-brown",
    foodResidue: "corn",
    stoolCharacter: "single-lump",
    dropStyle: "direct-hit",
    dropSound: "plaaank",
    exitCharacter: "free-flow",
    smell: "typical",
    paperSquares: "magic",
    rating: 5,
    aftermath: "soap-and-water",
    notes: "אירוע נקי, מדויק, עם תחושת סגירה מלאה.",
    createdAt: "2026-06-19T08:00:00.000Z"
  },
  {
    id: "seed-2",
    userId: "noya",
    userEmail: "noya@example.com",
    reporterName: "נועה",
    role: "אחראית משמרת",
    facility: "chemical-toilet",
    sittingTime: "up-to-15",
    peeTiming: "before",
    entertainment: "none",
    color: "light-brown",
    foodResidue: "none",
    stoolCharacter: "multiple-lumps",
    dropStyle: "porcelain-slide-marked",
    dropSound: "tink-tink-tink",
    exitCharacter: "sweaty-effort",
    smell: "unbearable",
    paperSquares: "up-to-30",
    rating: 2,
    aftermath: "alcohol-gel",
    notes: "החוויה תועדה לטובת ההיסטוריה בלבד.",
    createdAt: "2026-06-19T09:30:00.000Z"
  }
];
